name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          composer install
          npm install

      - name: Run Pest PHP tests
        run: |
          vendor/bin/pest

      # If tests pass, proceed with deployment
      - name: Install SSH client
        run: sudo apt-get install openssh-client

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no root@86.52.116.158 -p 23 'cd /var/www/school-admin &&
                               export COMPOSER_ALLOW_SUPERUSER=1 &&
                               git pull origin main &&
                               npm install &&
                               composer install &&
                               php artisan migrate --force &&
                               php artisan db:seed --force &&
                               npm run build'
